#!/usr/bin/env bash
# Scans a subdomain's record type and
# informs which IP is pointing to that record
#

domain="$1"                                         # Domain name to audit.
subdomain="$2"                                      # Specific subdomain to audit.

lookup_host() {
    host_record=$(
        dig "$1" | grep -A1 'ANSWER SECTION:' | tail -n 1
    )

    echo "$host_record" |
    awk '{print "The subdomain","'"$subdomain"'","is a",$4,"record and points to",$5}'
}

if [ "$domain" ] && [ "$subdomain" ] ; then         # Display information for the specified subdomain.
    host="$subdomain.$domain"                       # Concatenates the domain and subdomain.
    lookup_host "$host"
elif [ "$domain" ] ; then                           # Display information for its subdomains
    def_subdomains=(www lb-01 web-01 web-02)        # 'www', 'lb-01', 'web-01' and 'web-02'.
                                                    # In this specific order.
    for subdomain in "${def_subdomains[@]}" ; do
        host="$subdomain.$domain"
        lookup_host "$host"
    done
fi
