#!/usr/bin/env bash
# (FizzBuzz) Displays numbers from 1 to 100
i=1

while [ $i -le "100" ] ; do
    if ((i % 3 == 0 && i % 5 == 0)) ; then
        echo "FizzBuzz"
    elif ((i % 3 == 0)) ; then 
        echo "Fizz"
    elif ((i % 5 == 0)) ; then 
        echo "Buzz"
    else
        echo $i
    fi

    ((i += 1))
done
